const projects = [
  {
    title: 'Portraits!',
    image: './images/ffxivPortraitsCollage.webp',
    description: "Scraping all my gils for the pastel dyes :^)",
    tools: [],
    github: '',
    link: '',
  },
  {
    title: "At one of my friend's venue",
    image: './images/g1.webp',
    description: "Surprisingly enough, I've barely done any GPose. These were one of the few times I put in the effort haha.",
    tools: [],
    github: '',
    link: '',
  },
  {
    title: "Doinktrail",
    image: './images/g2.webp',
    description: "All hail dual dye channel!",
    tools: [],
    github: '',
    link: '',
  },
  {
    title: "Breaking habit",
    image: './images/g7.webp',
    description: "First time I used something other than the white-pink-blue combo :D",
    tools: ['ReactJs', 'Tailwind css'],
    github: '',
    link: '',
  },
  {
    title: "Contrast",
    image: './images/g6.webp',
    description: "In the newer glams, I just let the colors fight each other.",
    tools: ['ReactJs', 'Tailwind css'],
    github: '',
    link: '',
  },
  {
    title: "Focal point",
    image: './images/g5.webp',
    description: "Sometimes I just drop a random color into the mix.",
    tools: ['ReactJs', 'Tailwind css'],
    github: '',
    link: '',
  },
  {
    title: "Kitchen Sink",
    image: './images/g4.webp',
    description: "New palettes, alternating patches, random focal colors. Looks uglier than ever before :)",
    tools: ['ReactJs', 'Tailwind css'],
    github: '',
    link: '',
  },
];

export default projects;
